// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    memberships,
    routines,
    daysGroup,
    exerciseGroups,
    exercises,
    routineItems,
    routineSets,
    tSessions,
    tLogs,
    measurements,
  ];
  late final Shape0 accounts = Shape0(
      source: i0.VersionedTable(
        entityName: 'accounts',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 memberships = Shape1(
      source: i0.VersionedTable(
        entityName: 'memberships',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 routines = Shape2(
      source: i0.VersionedTable(
        entityName: 'routines',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_4,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
          _column_18,
          _column_19,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 daysGroup = Shape3(
      source: i0.VersionedTable(
        entityName: 'days_group',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_4,
          _column_12,
          _column_20,
          _column_13,
          _column_21,
          _column_17,
          _column_22,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 exerciseGroups = Shape4(
      source: i0.VersionedTable(
        entityName: 'exercise_groups',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(api_id)',
        ],
        columns: [
          _column_4,
          _column_23,
          _column_24,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 exercises = Shape5(
      source: i0.VersionedTable(
        entityName: 'exercises',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(api_id)',
        ],
        columns: [
          _column_4,
          _column_12,
          _column_25,
          _column_26,
          _column_27,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 routineItems = Shape6(
      source: i0.VersionedTable(
        entityName: 'routine_items',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_4,
          _column_12,
          _column_20,
          _column_13,
          _column_28,
          _column_17,
          _column_29,
          _column_30,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 routineSets = Shape7(
      source: i0.VersionedTable(
        entityName: 'routine_sets',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_4,
          _column_12,
          _column_31,
          _column_32,
          _column_13,
          _column_17,
          _column_33,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 tSessions = Shape8(
      source: i0.VersionedTable(
        entityName: 't_sessions',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_34,
          _column_35,
          _column_36,
          _column_37,
          _column_38,
          _column_12,
          _column_39,
          _column_40,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape9 tLogs = Shape9(
      source: i0.VersionedTable(
        entityName: 't_logs',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_41,
          _column_42,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_12,
          _column_39,
          _column_40,
          _column_48,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape10 measurements = Shape10(
      source: i0.VersionedTable(
        entityName: 'measurements',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_4,
          _column_12,
          _column_49,
          _column_46,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
          _column_54,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_59,
          _column_60,
          _column_61,
          _column_62,
          _column_63,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>('uid', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        additionalChecks: i1.GeneratedColumn.checkTextLength(
            minTextLength: 1, maxTextLength: 255),
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_3(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('created_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get planId =>
      columnsByName['plan_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get planName =>
      columnsByName['plan_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get startDate =>
      columnsByName['start_date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get endDate =>
      columnsByName['end_date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isGift =>
      columnsByName['is_gift']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('plan_id', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('plan_name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<double> _column_7(String aliasedName) =>
    i1.GeneratedColumn<double>('price', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<DateTime> _column_8(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('start_date', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_9(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('end_date', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<bool> _column_10(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_active', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_active" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_11(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_gift', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_gift" IN (0, 1))'));

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isCurrent =>
      columnsByName['is_current']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get isSynced =>
      columnsByName['is_synced']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>('api_id', aliasedName, true,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>('version', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        additionalChecks: i1.GeneratedColumn.checkTextLength(
            minTextLength: 1, maxTextLength: 50),
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>('description', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<bool> _column_16(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_current', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_current" IN (0, 1))'));
i1.GeneratedColumn<bool> _column_17(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_synced', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_synced" IN (0, 1))'));
i1.GeneratedColumn<DateTime> _column_18(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('created_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime,
        defaultValue: const CustomExpression(
            'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)'));
i1.GeneratedColumn<DateTime> _column_19(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('updated_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime,
        defaultValue: const CustomExpression(
            'CAST(strftime(\'%s\', CURRENT_TIMESTAMP) AS INTEGER)'));

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get index =>
      columnsByName['index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dayName =>
      columnsByName['day_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isSynced =>
      columnsByName['is_synced']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get routineId =>
      columnsByName['routine_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>('index', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>('day_name', aliasedName, false,
        additionalChecks: i1.GeneratedColumn.checkTextLength(
            minTextLength: 1, maxTextLength: 50),
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>('routine_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES routines (id) ON UPDATE CASCADE ON DELETE CASCADE'));

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get muscleGroupTranslations =>
      columnsByName['muscle_group_translations']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>('api_id', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>('muscle_group_translations', aliasedName, false,
        type: i1.DriftSqlType.string);

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageUrl =>
      columnsByName['image_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get muscleGroup =>
      columnsByName['muscle_group']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>('name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>('image_url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>('muscle_group', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES exercise_groups (id)'));

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get index =>
      columnsByName['index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get isSynced =>
      columnsByName['is_synced']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get exerciseId =>
      columnsByName['exercise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dayId =>
      columnsByName['day_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>('notes', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>('exercise_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES exercises (id) ON UPDATE CASCADE ON DELETE CASCADE'));
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>('day_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'REFERENCES days_group (id) ON UPDATE CASCADE ON DELETE CASCADE'));

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get roundIndex =>
      columnsByName['round_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repsCount =>
      columnsByName['reps_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isSynced =>
      columnsByName['is_synced']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get routineItemId =>
      columnsByName['routine_item_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>('round_index', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>('reps_count', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_33(String aliasedName) => i1.GeneratedColumn<
        int>('routine_item_id', aliasedName, false,
    type: i1.DriftSqlType.int,
    defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES routine_items (id) ON UPDATE CASCADE ON DELETE CASCADE'));

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get tsId =>
      columnsByName['ts_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dayId =>
      columnsByName['day_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get finishedAt =>
      columnsByName['finished_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<double> get progress =>
      columnsByName['progress']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isSynced =>
      columnsByName['is_synced']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>('ts_id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>('day_id', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<DateTime> _column_36(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('started_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<DateTime> _column_37(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('finished_at', aliasedName, true,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>('progress', aliasedName, false,
        type: i1.DriftSqlType.double,
        defaultValue: const CustomExpression('0.0'));
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>('version', aliasedName, false,
        type: i1.DriftSqlType.int, defaultValue: const CustomExpression('0'));
i1.GeneratedColumn<bool> _column_40(String aliasedName) =>
    i1.GeneratedColumn<bool>('is_synced', aliasedName, false,
        type: i1.DriftSqlType.bool,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
            'CHECK ("is_synced" IN (0, 1))'),
        defaultValue: const CustomExpression('0'));

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get logId =>
      columnsByName['log_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get exerciseId =>
      columnsByName['exercise_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get exerciseIndex =>
      columnsByName['exercise_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get setIndex =>
      columnsByName['set_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reps =>
      columnsByName['reps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get completedAt =>
      columnsByName['completed_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isSynced =>
      columnsByName['is_synced']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<int> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>('log_id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>('exercise_id', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>('exercise_index', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>('set_index', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>('reps', aliasedName, false,
        type: i1.DriftSqlType.int);
i1.GeneratedColumn<double> _column_46(String aliasedName) =>
    i1.GeneratedColumn<double>('weight', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<DateTime> _column_47(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('completed_at', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<int> _column_48(String aliasedName) => i1.GeneratedColumn<
        int>('session_id', aliasedName, false,
    type: i1.DriftSqlType.int,
    defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES t_sessions (ts_id) ON UPDATE CASCADE ON DELETE CASCADE'));

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get apiId =>
      columnsByName['api_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get height =>
      columnsByName['height']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lArm =>
      columnsByName['l_arm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rArm =>
      columnsByName['r_arm']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lHumerus =>
      columnsByName['l_humerus']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rHumerus =>
      columnsByName['r_humerus']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lThigh =>
      columnsByName['l_thigh']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rThigh =>
      columnsByName['r_thigh']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lLeg =>
      columnsByName['l_leg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get rLeg =>
      columnsByName['r_leg']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get neck =>
      columnsByName['neck']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get shoulders =>
      columnsByName['shoulders']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get waist =>
      columnsByName['waist']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get chest =>
      columnsByName['chest']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get hips =>
      columnsByName['hips']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get checkDate =>
      columnsByName['check_date']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<double> _column_49(String aliasedName) =>
    i1.GeneratedColumn<double>('height', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_50(String aliasedName) =>
    i1.GeneratedColumn<double>('l_arm', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_51(String aliasedName) =>
    i1.GeneratedColumn<double>('r_arm', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_52(String aliasedName) =>
    i1.GeneratedColumn<double>('l_humerus', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_53(String aliasedName) =>
    i1.GeneratedColumn<double>('r_humerus', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_54(String aliasedName) =>
    i1.GeneratedColumn<double>('l_thigh', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_55(String aliasedName) =>
    i1.GeneratedColumn<double>('r_thigh', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_56(String aliasedName) =>
    i1.GeneratedColumn<double>('l_leg', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_57(String aliasedName) =>
    i1.GeneratedColumn<double>('r_leg', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_58(String aliasedName) =>
    i1.GeneratedColumn<double>('neck', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_59(String aliasedName) =>
    i1.GeneratedColumn<double>('shoulders', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_60(String aliasedName) =>
    i1.GeneratedColumn<double>('waist', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_61(String aliasedName) =>
    i1.GeneratedColumn<double>('chest', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<double> _column_62(String aliasedName) =>
    i1.GeneratedColumn<double>('hips', aliasedName, false,
        type: i1.DriftSqlType.double);
i1.GeneratedColumn<DateTime> _column_63(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('check_date', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
    ));
