// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/practice/practice_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/practice_models/t_log_model.dart'
    as _i5;
import 'package:uniceps/app/data/models/practice_models/t_session_model.dart'
    as _i4;
import 'package:uniceps/app/data/models/routine_models/routine_day_dto.dart'
    as _i3;
import 'package:uniceps/app/data/models/routine_models/routine_dto.dart' as _i8;
import 'package:uniceps/app/data/sources/local/dal_practice/t_session_local_source.dart'
    as _i6;
import 'package:uniceps/app/domain/classes/routine_classes/routine_heat.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTuple2_0<T1, T2> extends _i1.SmartFake
    implements _i2.Tuple2<T1, T2> {
  _FakeTuple2_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutineDayDto_1 extends _i1.SmartFake implements _i3.RoutineDayDto {
  _FakeRoutineDayDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTSessionModel_2 extends _i1.SmartFake implements _i4.TSessionModel {
  _FakeTSessionModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTLogModel_3 extends _i1.SmartFake implements _i5.TLogModel {
  _FakeTLogModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ITSessionLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockITSessionLocalSourceContract extends _i1.Mock
    implements _i6.ITSessionLocalSourceContract {
  MockITSessionLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Tuple2<_i8.RoutineDto?, int?>> getCurrentRoutine() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentRoutine, []),
            returnValue: _i7.Future<_i2.Tuple2<_i8.RoutineDto?, int?>>.value(
              _FakeTuple2_0<_i8.RoutineDto?, int?>(
                this,
                Invocation.method(#getCurrentRoutine, []),
              ),
            ),
          )
          as _i7.Future<_i2.Tuple2<_i8.RoutineDto?, int?>>);

  @override
  _i7.Future<_i2.Tuple2<_i8.RoutineDto?, _i9.RoutineHeat?>>
  getCurrentRoutineWithHeat() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentRoutineWithHeat, []),
            returnValue:
                _i7.Future<_i2.Tuple2<_i8.RoutineDto?, _i9.RoutineHeat?>>.value(
                  _FakeTuple2_0<_i8.RoutineDto?, _i9.RoutineHeat?>(
                    this,
                    Invocation.method(#getCurrentRoutineWithHeat, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Tuple2<_i8.RoutineDto?, _i9.RoutineHeat?>>);

  @override
  _i7.Future<_i3.RoutineDayDto> getPracticeDay(int? dayId) =>
      (super.noSuchMethod(
            Invocation.method(#getPracticeDay, [dayId]),
            returnValue: _i7.Future<_i3.RoutineDayDto>.value(
              _FakeRoutineDayDto_1(
                this,
                Invocation.method(#getPracticeDay, [dayId]),
              ),
            ),
          )
          as _i7.Future<_i3.RoutineDayDto>);

  @override
  _i7.Future<List<_i4.TSessionModel>> getSessionsByRoutine(int? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsByRoutine, [routineId]),
            returnValue: _i7.Future<List<_i4.TSessionModel>>.value(
              <_i4.TSessionModel>[],
            ),
          )
          as _i7.Future<List<_i4.TSessionModel>>);

  @override
  _i7.Future<_i4.TSessionModel?> getPreviousSession() =>
      (super.noSuchMethod(
            Invocation.method(#getPreviousSession, []),
            returnValue: _i7.Future<_i4.TSessionModel?>.value(),
          )
          as _i7.Future<_i4.TSessionModel?>);

  @override
  _i7.Future<_i4.TSessionModel> startTrainingSession(
    int? dayId,
    String? dayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startTrainingSession, [dayId, dayName]),
            returnValue: _i7.Future<_i4.TSessionModel>.value(
              _FakeTSessionModel_2(
                this,
                Invocation.method(#startTrainingSession, [dayId, dayName]),
              ),
            ),
          )
          as _i7.Future<_i4.TSessionModel>);

  @override
  _i7.Future<_i5.TLogModel> logSet(
    _i5.TLogModel? log,
    double? sessionProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logSet, [log, sessionProgress]),
            returnValue: _i7.Future<_i5.TLogModel>.value(
              _FakeTLogModel_3(
                this,
                Invocation.method(#logSet, [log, sessionProgress]),
              ),
            ),
          )
          as _i7.Future<_i5.TLogModel>);

  @override
  _i7.Future<void> finishTrainingSession(
    _i4.TSessionModel? session,
    bool? isFullSession,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#finishTrainingSession, [session, isFullSession]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
