// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/profile/measurements_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/profile_models/measurement_model.dart'
    as _i4;
import 'package:uniceps/app/data/sources/local/dal_measurements/measurements_local_source.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IMeasurementsLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMeasurementsLocalSource extends _i1.Mock
    implements _i2.IMeasurementsLocalSource {
  MockIMeasurementsLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MeasurementModel>> getMeasurements() =>
      (super.noSuchMethod(
            Invocation.method(#getMeasurements, []),
            returnValue: _i3.Future<List<_i4.MeasurementModel>>.value(
              <_i4.MeasurementModel>[],
            ),
          )
          as _i3.Future<List<_i4.MeasurementModel>>);

  @override
  _i3.Future<int> saveMeasurement(_i4.MeasurementModel? m) =>
      (super.noSuchMethod(
            Invocation.method(#saveMeasurement, [m]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> upsertMeasurement(_i4.MeasurementModel? m) =>
      (super.noSuchMethod(
            Invocation.method(#upsertMeasurement, [m]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMeasurement(_i4.MeasurementModel? m) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeasurement, [m]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.MeasurementModel>> getAllUnSyncedMeasurements() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUnSyncedMeasurements, []),
            returnValue: _i3.Future<List<_i4.MeasurementModel>>.value(
              <_i4.MeasurementModel>[],
            ),
          )
          as _i3.Future<List<_i4.MeasurementModel>>);

  @override
  _i3.Future<DateTime?> getLastMeasurementSync() =>
      (super.noSuchMethod(
            Invocation.method(#getLastMeasurementSync, []),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);
}
