// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/profile/profile_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/auth_models/profile_model.dart' as _i2;
import 'package:uniceps/app/data/sources/local/dal_profile/profile_local_source.dart' as _i3;
import 'package:uniceps/app/data/sources/remote/dal_profile/profile_remote_source.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlayerModel_0 extends _i1.SmartFake implements _i2.ProfileModel {
  _FakePlayerModel_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [IProfileLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileLocalSource extends _i1.Mock implements _i3.IProfileLocalSource {
  MockIProfileLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProfileModel> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i4.Future<_i2.ProfileModel>.value(
              _FakePlayerModel_0(this, Invocation.method(#getProfileData, [])),
            ),
          )
          as _i4.Future<_i2.ProfileModel>);

  @override
  _i4.Future<void> savePlayerData(_i2.ProfileModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#savePlayerData, [model]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [IProfileRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRemoteSource extends _i1.Mock implements _i5.IProfileRemoteSource {
  MockIProfileRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> uploadProfile(_i2.ProfileModel? profile) =>
      (super.noSuchMethod(Invocation.method(#uploadProfile, [profile]), returnValue: _i4.Future<bool>.value(false))
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> uploadPhoto(String? path) =>
      (super.noSuchMethod(Invocation.method(#uploadPhoto, [path]), returnValue: _i4.Future<bool>.value(false))
          as _i4.Future<bool>);
}
