// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/performance/performance_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/auth_models/player_model.dart' as _i2;
import 'package:uniceps/app/data/models/practice_models/t_log_model.dart'
    as _i7;
import 'package:uniceps/app/data/models/practice_models/t_session_model.dart'
    as _i6;
import 'package:uniceps/app/data/models/profile_models/measurement_model.dart'
    as _i15;
import 'package:uniceps/app/data/models/routine_models/routine_day_dto.dart'
    as _i5;
import 'package:uniceps/app/data/models/routine_models/routine_dto.dart' as _i3;
import 'package:uniceps/app/data/models/routine_result.dart' as _i12;
import 'package:uniceps/app/data/sources/local/dal_measurements/measurements_local_source.dart'
    as _i14;
import 'package:uniceps/app/data/sources/local/dal_practice/t_session_local_source.dart'
    as _i13;
import 'package:uniceps/app/data/sources/local/dal_profile/profile_local_source.dart'
    as _i8;
import 'package:uniceps/app/data/sources/local/dal_routine/routine_management_local_source.dart'
    as _i10;
import 'package:uniceps/app/domain/classes/routine_classes/routine_heat.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlayerModel_0 extends _i1.SmartFake implements _i2.PlayerModel {
  _FakePlayerModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutineDto_1 extends _i1.SmartFake implements _i3.RoutineDto {
  _FakeRoutineDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTuple2_2<T1, T2> extends _i1.SmartFake
    implements _i4.Tuple2<T1, T2> {
  _FakeTuple2_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoutineDayDto_3 extends _i1.SmartFake implements _i5.RoutineDayDto {
  _FakeRoutineDayDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTSessionModel_4 extends _i1.SmartFake implements _i6.TSessionModel {
  _FakeTSessionModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTLogModel_5 extends _i1.SmartFake implements _i7.TLogModel {
  _FakeTLogModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IProfileLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileLocalSource extends _i1.Mock
    implements _i8.IProfileLocalSource {
  MockIProfileLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.PlayerModel> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i9.Future<_i2.PlayerModel>.value(
              _FakePlayerModel_0(this, Invocation.method(#getProfileData, [])),
            ),
          )
          as _i9.Future<_i2.PlayerModel>);

  @override
  _i9.Future<void> savePlayerData(_i2.PlayerModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#savePlayerData, [model]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [IRoutineManagementLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRoutineManagementLocalSourceContract extends _i1.Mock
    implements _i10.IRoutineManagementLocalSourceContract {
  MockIRoutineManagementLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i3.RoutineDto>> getAllRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutines, []),
            returnValue: _i9.Future<List<_i3.RoutineDto>>.value(
              <_i3.RoutineDto>[],
            ),
          )
          as _i9.Future<List<_i3.RoutineDto>>);

  @override
  _i9.Future<List<({_i11.RoutineHeat heat, _i3.RoutineDto routine})>>
  getAllRoutinesWithHeat() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutinesWithHeat, []),
            returnValue:
                _i9.Future<
                  List<({_i11.RoutineHeat heat, _i3.RoutineDto routine})>
                >.value(<({_i11.RoutineHeat heat, _i3.RoutineDto routine})>[]),
          )
          as _i9.Future<
            List<({_i11.RoutineHeat heat, _i3.RoutineDto routine})>
          >);

  @override
  _i9.Future<_i3.RoutineDto> createRoutine(String? routineName) =>
      (super.noSuchMethod(
            Invocation.method(#createRoutine, [routineName]),
            returnValue: _i9.Future<_i3.RoutineDto>.value(
              _FakeRoutineDto_1(
                this,
                Invocation.method(#createRoutine, [routineName]),
              ),
            ),
          )
          as _i9.Future<_i3.RoutineDto>);

  @override
  _i9.Future<_i3.RoutineDto> updateRoutine(_i3.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoutine, [dto]),
            returnValue: _i9.Future<_i3.RoutineDto>.value(
              _FakeRoutineDto_1(this, Invocation.method(#updateRoutine, [dto])),
            ),
          )
          as _i9.Future<_i3.RoutineDto>);

  @override
  _i9.Future<void> setCurrentRoutine(_i3.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentRoutine, [dto]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteRoutine(_i3.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoutine, [dto]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<_i12.Stage> insertFullRoutine(_i3.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#insertFullRoutine, [dto]),
            returnValue: _i9.Stream<_i12.Stage>.empty(),
          )
          as _i9.Stream<_i12.Stage>);

  @override
  _i9.Future<_i3.RoutineDto> getFullRoutine(int? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#getFullRoutine, [routineId]),
            returnValue: _i9.Future<_i3.RoutineDto>.value(
              _FakeRoutineDto_1(
                this,
                Invocation.method(#getFullRoutine, [routineId]),
              ),
            ),
          )
          as _i9.Future<_i3.RoutineDto>);
}

/// A class which mocks [ITSessionLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockITSessionLocalSourceContract extends _i1.Mock
    implements _i13.ITSessionLocalSourceContract {
  MockITSessionLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i4.Tuple2<_i3.RoutineDto?, int?>> getCurrentRoutine() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentRoutine, []),
            returnValue: _i9.Future<_i4.Tuple2<_i3.RoutineDto?, int?>>.value(
              _FakeTuple2_2<_i3.RoutineDto?, int?>(
                this,
                Invocation.method(#getCurrentRoutine, []),
              ),
            ),
          )
          as _i9.Future<_i4.Tuple2<_i3.RoutineDto?, int?>>);

  @override
  _i9.Future<_i4.Tuple2<_i3.RoutineDto?, _i11.RoutineHeat?>>
  getCurrentRoutineWithHeat() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentRoutineWithHeat, []),
            returnValue:
                _i9.Future<
                  _i4.Tuple2<_i3.RoutineDto?, _i11.RoutineHeat?>
                >.value(
                  _FakeTuple2_2<_i3.RoutineDto?, _i11.RoutineHeat?>(
                    this,
                    Invocation.method(#getCurrentRoutineWithHeat, []),
                  ),
                ),
          )
          as _i9.Future<_i4.Tuple2<_i3.RoutineDto?, _i11.RoutineHeat?>>);

  @override
  _i9.Future<_i5.RoutineDayDto> getPracticeDay(int? dayId) =>
      (super.noSuchMethod(
            Invocation.method(#getPracticeDay, [dayId]),
            returnValue: _i9.Future<_i5.RoutineDayDto>.value(
              _FakeRoutineDayDto_3(
                this,
                Invocation.method(#getPracticeDay, [dayId]),
              ),
            ),
          )
          as _i9.Future<_i5.RoutineDayDto>);

  @override
  _i9.Future<List<_i6.TSessionModel>> getSessionsByRoutine(int? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionsByRoutine, [routineId]),
            returnValue: _i9.Future<List<_i6.TSessionModel>>.value(
              <_i6.TSessionModel>[],
            ),
          )
          as _i9.Future<List<_i6.TSessionModel>>);

  @override
  _i9.Future<_i6.TSessionModel?> getPreviousSession() =>
      (super.noSuchMethod(
            Invocation.method(#getPreviousSession, []),
            returnValue: _i9.Future<_i6.TSessionModel?>.value(),
          )
          as _i9.Future<_i6.TSessionModel?>);

  @override
  _i9.Future<_i6.TSessionModel> startTrainingSession(
    int? dayId,
    String? dayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startTrainingSession, [dayId, dayName]),
            returnValue: _i9.Future<_i6.TSessionModel>.value(
              _FakeTSessionModel_4(
                this,
                Invocation.method(#startTrainingSession, [dayId, dayName]),
              ),
            ),
          )
          as _i9.Future<_i6.TSessionModel>);

  @override
  _i9.Future<_i7.TLogModel> logSet(
    _i7.TLogModel? log,
    double? sessionProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logSet, [log, sessionProgress]),
            returnValue: _i9.Future<_i7.TLogModel>.value(
              _FakeTLogModel_5(
                this,
                Invocation.method(#logSet, [log, sessionProgress]),
              ),
            ),
          )
          as _i9.Future<_i7.TLogModel>);

  @override
  _i9.Future<void> finishTrainingSession(
    _i6.TSessionModel? session,
    bool? isFullSession,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#finishTrainingSession, [session, isFullSession]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [IMeasurementsLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMeasurementsLocalSource extends _i1.Mock
    implements _i14.IMeasurementsLocalSource {
  MockIMeasurementsLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i15.MeasurementModel>> getMeasurements() =>
      (super.noSuchMethod(
            Invocation.method(#getMeasurements, []),
            returnValue: _i9.Future<List<_i15.MeasurementModel>>.value(
              <_i15.MeasurementModel>[],
            ),
          )
          as _i9.Future<List<_i15.MeasurementModel>>);

  @override
  _i9.Future<int> saveMeasurement(_i15.MeasurementModel? m) =>
      (super.noSuchMethod(
            Invocation.method(#saveMeasurement, [m]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<void> deleteMeasurement(_i15.MeasurementModel? m) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeasurement, [m]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
