// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/account/account_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:logger/logger.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/account_models/account_model.dart'
    as _i2;
import 'package:uniceps/app/data/models/account_models/membership_model.dart'
    as _i3;
import 'package:uniceps/app/data/models/account_models/payment_response.dart'
    as _i5;
import 'package:uniceps/app/data/models/account_models/plan_item_model.dart'
    as _i10;
import 'package:uniceps/app/data/models/account_models/plan_model.dart' as _i4;
import 'package:uniceps/app/data/sources/local/dal_account/account_local_source.dart'
    as _i7;
import 'package:uniceps/app/data/sources/remote/dal_account/account_remote_source.dart'
    as _i9;
import 'package:uniceps/app/data/sources/services/token/token_contract.dart'
    as _i6;
import 'package:uniceps/app/data/sources/services/token/token_service_simple.dart'
    as _i12;
import 'package:uniceps/app/services/network_info.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAccountModel_0 extends _i1.SmartFake implements _i2.AccountModel {
  _FakeAccountModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMembershipModel_1 extends _i1.SmartFake
    implements _i3.MembershipModel {
  _FakeMembershipModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlanModel_2 extends _i1.SmartFake implements _i4.PlanModel {
  _FakePlanModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePaymentResponse_3 extends _i1.SmartFake
    implements _i5.PaymentResponse {
  _FakePaymentResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_4 extends _i1.SmartFake implements _i6.Session {
  _FakeSession_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAccountLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAccountLocalSource extends _i1.Mock
    implements _i7.IAccountLocalSource {
  MockIAccountLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.AccountModel> getUserAccount() =>
      (super.noSuchMethod(
            Invocation.method(#getUserAccount, []),
            returnValue: _i8.Future<_i2.AccountModel>.value(
              _FakeAccountModel_0(this, Invocation.method(#getUserAccount, [])),
            ),
          )
          as _i8.Future<_i2.AccountModel>);

  @override
  _i8.Future<_i3.MembershipModel> getCurrentPlan() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPlan, []),
            returnValue: _i8.Future<_i3.MembershipModel>.value(
              _FakeMembershipModel_1(
                this,
                Invocation.method(#getCurrentPlan, []),
              ),
            ),
          )
          as _i8.Future<_i3.MembershipModel>);

  @override
  _i8.Future<void> saveUserAccount(_i2.AccountModel? userAccount) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserAccount, [userAccount]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> saveUserMembership(_i3.MembershipModel? subscriptionPlan) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserMembership, [subscriptionPlan]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.MembershipModel> userMembershipNotified() =>
      (super.noSuchMethod(
            Invocation.method(#userMembershipNotified, []),
            returnValue: _i8.Future<_i3.MembershipModel>.value(
              _FakeMembershipModel_1(
                this,
                Invocation.method(#userMembershipNotified, []),
              ),
            ),
          )
          as _i8.Future<_i3.MembershipModel>);

  @override
  _i8.Future<void> clearMemberships() =>
      (super.noSuchMethod(
            Invocation.method(#clearMemberships, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [IAccountRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAccountRemoteSource extends _i1.Mock
    implements _i9.IAccountRemoteSource {
  MockIAccountRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.MembershipModel> getUserMembership() =>
      (super.noSuchMethod(
            Invocation.method(#getUserMembership, []),
            returnValue: _i8.Future<_i3.MembershipModel>.value(
              _FakeMembershipModel_1(
                this,
                Invocation.method(#getUserMembership, []),
              ),
            ),
          )
          as _i8.Future<_i3.MembershipModel>);

  @override
  _i8.Future<_i4.PlanModel> getPlans() =>
      (super.noSuchMethod(
            Invocation.method(#getPlans, []),
            returnValue: _i8.Future<_i4.PlanModel>.value(
              _FakePlanModel_2(this, Invocation.method(#getPlans, [])),
            ),
          )
          as _i8.Future<_i4.PlanModel>);

  @override
  _i8.Future<_i5.PaymentResponse> buyPlan(_i10.PlanItemModel? item) =>
      (super.noSuchMethod(
            Invocation.method(#buyPlan, [item]),
            returnValue: _i8.Future<_i5.PaymentResponse>.value(
              _FakePaymentResponse_3(this, Invocation.method(#buyPlan, [item])),
            ),
          )
          as _i8.Future<_i5.PaymentResponse>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}

/// A class which mocks [SimpleTokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimpleTokenService extends _i1.Mock
    implements _i12.SimpleTokenService {
  MockSimpleTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> saveAccessToken(String? accessToken, DateTime? expireDate) =>
      (super.noSuchMethod(
            Invocation.method(#saveAccessToken, [accessToken, expireDate]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<bool> isTokenValid() =>
      (super.noSuchMethod(
            Invocation.method(#isTokenValid, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> refreshToken(String? oldToken) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [oldToken]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccessToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.Session> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i8.Future<_i6.Session>.value(
              _FakeSession_4(this, Invocation.method(#getSession, [])),
            ),
          )
          as _i8.Future<_i6.Session>);

  @override
  _i8.Future<void> setSession(_i6.Session? s) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [s]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i13.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> get init =>
      (super.noSuchMethod(
            Invocation.getter(#init),
            returnValue: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #v,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #t,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #d,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #i,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #w,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #wtf,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #f,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i13.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isClosed() =>
      (super.noSuchMethod(Invocation.method(#isClosed, []), returnValue: false)
          as bool);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
