// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/routine/exercises_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/routine_models/exercise_dto.dart'
    as _i5;
import 'package:uniceps/app/data/models/routine_models/muscle_group_dto.dart'
    as _i4;
import 'package:uniceps/app/data/sources/local/dal_routine/exercises_local_source.dart'
    as _i7;
import 'package:uniceps/app/data/sources/remote/dal_routine/exercises_remote_source.dart'
    as _i2;
import 'package:uniceps/app/services/network_info.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IExercisesRemoteSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIExercisesRemoteSourceContract extends _i1.Mock
    implements _i2.IExercisesRemoteSourceContract {
  MockIExercisesRemoteSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MuscleGroupDto>> getExerciseGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseGroups, []),
            returnValue: _i3.Future<List<_i4.MuscleGroupDto>>.value(
              <_i4.MuscleGroupDto>[],
            ),
          )
          as _i3.Future<List<_i4.MuscleGroupDto>>);

  @override
  _i3.Future<List<_i5.ExerciseDto>> getAllExercises([DateTime? timestamp]) =>
      (super.noSuchMethod(
            Invocation.method(#getAllExercises, [timestamp]),
            returnValue: _i3.Future<List<_i5.ExerciseDto>>.value(
              <_i5.ExerciseDto>[],
            ),
          )
          as _i3.Future<List<_i5.ExerciseDto>>);

  @override
  _i3.Future<List<_i5.ExerciseDto>> getExercisesByGroup(
    _i4.MuscleGroupDto? group,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByGroup, [group]),
            returnValue: _i3.Future<List<_i5.ExerciseDto>>.value(
              <_i5.ExerciseDto>[],
            ),
          )
          as _i3.Future<List<_i5.ExerciseDto>>);

  @override
  _i3.Future<_i6.Uint8List> getExerciseImage(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseImage, [imageUrl]),
            returnValue: _i3.Future<_i6.Uint8List>.value(_i6.Uint8List(0)),
          )
          as _i3.Future<_i6.Uint8List>);
}

/// A class which mocks [IExercisesLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIExercisesLocalSourceContract extends _i1.Mock
    implements _i7.IExercisesLocalSourceContract {
  MockIExercisesLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.ExerciseDto>> getExercises() =>
      (super.noSuchMethod(
            Invocation.method(#getExercises, []),
            returnValue: _i3.Future<List<_i5.ExerciseDto>>.value(
              <_i5.ExerciseDto>[],
            ),
          )
          as _i3.Future<List<_i5.ExerciseDto>>);

  @override
  _i3.Future<List<_i5.ExerciseDto>> getExercisesByGroup(String? groupId) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisesByGroup, [groupId]),
            returnValue: _i3.Future<List<_i5.ExerciseDto>>.value(
              <_i5.ExerciseDto>[],
            ),
          )
          as _i3.Future<List<_i5.ExerciseDto>>);

  @override
  _i3.Future<void> saveExerciseImage(String? exId, _i6.Uint8List? bitmap) =>
      (super.noSuchMethod(
            Invocation.method(#saveExerciseImage, [exId, bitmap]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> writeExercise(_i5.ExerciseDto? e) =>
      (super.noSuchMethod(
            Invocation.method(#writeExercise, [e]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
