// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/routine/routine_with_heat_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i10;

import 'package:logger/logger.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/routine_models/routine_dto.dart' as _i2;
import 'package:uniceps/app/data/models/routine_result.dart' as _i7;
import 'package:uniceps/app/data/sources/local/dal_routine/routine_management_local_source.dart'
    as _i4;
import 'package:uniceps/app/data/sources/services/import/file_parse_service.dart'
    as _i8;
import 'package:uniceps/app/data/sources/services/import/unifile.dart' as _i3;
import 'package:uniceps/app/data/sources/services/media_helper.dart' as _i9;
import 'package:uniceps/app/domain/classes/routine_classes/routine_heat.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoutineDto_0 extends _i1.SmartFake implements _i2.RoutineDto {
  _FakeRoutineDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUniFile_1 extends _i1.SmartFake implements _i3.UniFile {
  _FakeUniFile_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IRoutineManagementLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRoutineManagementLocalSourceContract extends _i1.Mock
    implements _i4.IRoutineManagementLocalSourceContract {
  MockIRoutineManagementLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.RoutineDto>> getAllRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutines, []),
            returnValue: _i5.Future<List<_i2.RoutineDto>>.value(
              <_i2.RoutineDto>[],
            ),
          )
          as _i5.Future<List<_i2.RoutineDto>>);

  @override
  _i5.Future<List<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>>
  getAllRoutinesWithHeat() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutinesWithHeat, []),
            returnValue:
                _i5.Future<
                  List<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>
                >.value(<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>[]),
          )
          as _i5.Future<
            List<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>
          >);

  @override
  _i5.Future<_i2.RoutineDto> createRoutine(String? routineName) =>
      (super.noSuchMethod(
            Invocation.method(#createRoutine, [routineName]),
            returnValue: _i5.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(
                this,
                Invocation.method(#createRoutine, [routineName]),
              ),
            ),
          )
          as _i5.Future<_i2.RoutineDto>);

  @override
  _i5.Future<_i2.RoutineDto> updateRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoutine, [dto]),
            returnValue: _i5.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(this, Invocation.method(#updateRoutine, [dto])),
            ),
          )
          as _i5.Future<_i2.RoutineDto>);

  @override
  _i5.Future<void> setCurrentRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentRoutine, [dto]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoutine, [dto]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i7.Stage> insertFullRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#insertFullRoutine, [dto]),
            returnValue: _i5.Stream<_i7.Stage>.empty(),
          )
          as _i5.Stream<_i7.Stage>);

  @override
  _i5.Future<_i2.RoutineDto> getFullRoutine(int? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#getFullRoutine, [routineId]),
            returnValue: _i5.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(
                this,
                Invocation.method(#getFullRoutine, [routineId]),
              ),
            ),
          )
          as _i5.Future<_i2.RoutineDto>);
}

/// A class which mocks [UniFileManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUniFileManager extends _i1.Mock implements _i8.UniFileManager {
  MockUniFileManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.UniFile> importFile() =>
      (super.noSuchMethod(
            Invocation.method(#importFile, []),
            returnValue: _i5.Future<_i3.UniFile>.value(
              _FakeUniFile_1(this, Invocation.method(#importFile, [])),
            ),
          )
          as _i5.Future<_i3.UniFile>);

  @override
  _i5.Future<void> exportRoutineToFile({
    required String? fileName,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportRoutineToFile, [], {
              #fileName: fileName,
              #data: data,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [MediaHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaHelper extends _i1.Mock implements _i9.MediaHelper {
  MockMediaHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i10.Uint8List?> getImage(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getImage, [imageUrl]),
            returnValue: _i5.Future<_i10.Uint8List?>.value(),
          )
          as _i5.Future<_i10.Uint8List?>);

  @override
  _i5.Stream<double> saveImages(List<String>? imageUrls) =>
      (super.noSuchMethod(
            Invocation.method(#saveImages, [imageUrls]),
            returnValue: _i5.Stream<double>.empty(),
          )
          as _i5.Stream<double>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i11.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> get init =>
      (super.noSuchMethod(
            Invocation.getter(#init),
            returnValue: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #v,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #t,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #d,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #i,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #w,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #wtf,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #f,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i11.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isClosed() =>
      (super.noSuchMethod(Invocation.method(#isClosed, []), returnValue: false)
          as bool);

  @override
  _i5.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
