// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/routine/routine_days_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:logger/src/log_level.dart' as _i6;
import 'package:logger/src/logger.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/routine_models/routine_day_dto.dart'
    as _i2;
import 'package:uniceps/app/data/sources/local/dal_routine/routine_days_local_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoutineDayDto_0 extends _i1.SmartFake implements _i2.RoutineDayDto {
  _FakeRoutineDayDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IRoutineDaysLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRoutineDaysLocalSourceContract extends _i1.Mock
    implements _i3.IRoutineDaysLocalSourceContract {
  MockIRoutineDaysLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.RoutineDayDto>> getDays(int? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#getDays, [routineId]),
            returnValue: _i4.Future<List<_i2.RoutineDayDto>>.value(
              <_i2.RoutineDayDto>[],
            ),
          )
          as _i4.Future<List<_i2.RoutineDayDto>>);

  @override
  _i4.Future<_i2.RoutineDayDto> addDay(_i2.RoutineDayDto? day) =>
      (super.noSuchMethod(
            Invocation.method(#addDay, [day]),
            returnValue: _i4.Future<_i2.RoutineDayDto>.value(
              _FakeRoutineDayDto_0(this, Invocation.method(#addDay, [day])),
            ),
          )
          as _i4.Future<_i2.RoutineDayDto>);

  @override
  _i4.Future<void> renameDay(_i2.RoutineDayDto? day) =>
      (super.noSuchMethod(
            Invocation.method(#renameDay, [day]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeDay(_i2.RoutineDayDto? day) =>
      (super.noSuchMethod(
            Invocation.method(#removeDay, [day]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.RoutineDayDto>> saveOrder(
    List<_i2.RoutineDayDto>? days,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveOrder, [days]),
            returnValue: _i4.Future<List<_i2.RoutineDayDto>>.value(
              <_i2.RoutineDayDto>[],
            ),
          )
          as _i4.Future<List<_i2.RoutineDayDto>>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i5.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> get init =>
      (super.noSuchMethod(
            Invocation.getter(#init),
            returnValue: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void v(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #v,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void t(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #t,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void d(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #d,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void i(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #i,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void w(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #w,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void e(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #e,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void wtf(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #wtf,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void f(
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #f,
      [message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void log(
    _i6.Level? level,
    dynamic message, {
    DateTime? time,
    Object? error,
    StackTrace? stackTrace,
  }) => super.noSuchMethod(
    Invocation.method(
      #log,
      [level, message],
      {#time: time, #error: error, #stackTrace: stackTrace},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool isClosed() =>
      (super.noSuchMethod(Invocation.method(#isClosed, []), returnValue: false)
          as bool);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
