// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/routine/routine_items_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uniceps/app/data/models/routine_models/routine_item_dto.dart'
    as _i4;
import 'package:uniceps/app/data/sources/local/dal_routine/routine_items_local_source.dart'
    as _i2;
import 'package:uniceps/app/data/sources/services/media_helper.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IRoutineItemsLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRoutineItemsLocalSourceContract extends _i1.Mock
    implements _i2.IRoutineItemsLocalSourceContract {
  MockIRoutineItemsLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RoutineItemDto>> getItemsByDay(int? dayId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByDay, [dayId]),
            returnValue: _i3.Future<List<_i4.RoutineItemDto>>.value(
              <_i4.RoutineItemDto>[],
            ),
          )
          as _i3.Future<List<_i4.RoutineItemDto>>);

  @override
  _i3.Future<List<_i4.RoutineItemDto>> addItems(
    List<_i4.RoutineItemDto>? list,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addItems, [list]),
            returnValue: _i3.Future<List<_i4.RoutineItemDto>>.value(
              <_i4.RoutineItemDto>[],
            ),
          )
          as _i3.Future<List<_i4.RoutineItemDto>>);

  @override
  _i3.Future<List<_i4.RoutineItemDto>> reorderItems(
    List<_i4.RoutineItemDto>? list,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderItems, [list]),
            returnValue: _i3.Future<List<_i4.RoutineItemDto>>.value(
              <_i4.RoutineItemDto>[],
            ),
          )
          as _i3.Future<List<_i4.RoutineItemDto>>);

  @override
  _i3.Future<void> removeItem(_i4.RoutineItemDto? item) =>
      (super.noSuchMethod(
            Invocation.method(#removeItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> copySetsToAll(int? dayId, int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#copySetsToAll, [dayId, itemId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [MediaHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaHelper extends _i1.Mock implements _i5.MediaHelper {
  MockMediaHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Uint8List?> getImage(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getImage, [imageUrl]),
            returnValue: _i3.Future<_i6.Uint8List?>.value(),
          )
          as _i3.Future<_i6.Uint8List?>);

  @override
  _i3.Stream<double> saveImages(List<String>? imageUrls) =>
      (super.noSuchMethod(
            Invocation.method(#saveImages, [imageUrls]),
            returnValue: _i3.Stream<double>.empty(),
          )
          as _i3.Stream<double>);
}
