// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/routine/routine_management_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:uniceps/app/data/models/routine_models/routine_dto.dart' as _i2;
import 'package:uniceps/app/data/models/routine_result.dart' as _i6;
import 'package:uniceps/app/data/sources/local/dal_routine/routine_management_local_source.dart'
    as _i4;
import 'package:uniceps/app/data/sources/services/internet_client/client_helper.dart'
    as _i8;
import 'package:uniceps/app/domain/classes/routine_classes/routine_heat.dart'
    as _i5;
import 'package:uniceps/app/services/network_info.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoutineDto_0 extends _i1.SmartFake implements _i2.RoutineDto {
  _FakeRoutineDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IRoutineManagementLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRoutineManagementLocalSourceContract extends _i1.Mock
    implements _i4.IRoutineManagementLocalSourceContract {
  MockIRoutineManagementLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.RoutineDto>> getAllRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutines, []),
            returnValue: _i3.Future<List<_i2.RoutineDto>>.value(
              <_i2.RoutineDto>[],
            ),
          )
          as _i3.Future<List<_i2.RoutineDto>>);

  @override
  _i3.Future<List<({_i5.RoutineHeat heat, _i2.RoutineDto routine})>>
  getAllRoutinesWithHeat() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutinesWithHeat, []),
            returnValue:
                _i3.Future<
                  List<({_i5.RoutineHeat heat, _i2.RoutineDto routine})>
                >.value(<({_i5.RoutineHeat heat, _i2.RoutineDto routine})>[]),
          )
          as _i3.Future<
            List<({_i5.RoutineHeat heat, _i2.RoutineDto routine})>
          >);

  @override
  _i3.Future<_i2.RoutineDto> createRoutine(String? routineName) =>
      (super.noSuchMethod(
            Invocation.method(#createRoutine, [routineName]),
            returnValue: _i3.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(
                this,
                Invocation.method(#createRoutine, [routineName]),
              ),
            ),
          )
          as _i3.Future<_i2.RoutineDto>);

  @override
  _i3.Future<_i2.RoutineDto> updateRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoutine, [dto]),
            returnValue: _i3.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(this, Invocation.method(#updateRoutine, [dto])),
            ),
          )
          as _i3.Future<_i2.RoutineDto>);

  @override
  _i3.Future<void> setCurrentRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentRoutine, [dto]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoutine, [dto]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i6.Stage> insertFullRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#insertFullRoutine, [dto]),
            returnValue: _i3.Stream<_i6.Stage>.empty(),
          )
          as _i3.Stream<_i6.Stage>);

  @override
  _i3.Future<_i2.RoutineDto> getFullRoutine(int? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#getFullRoutine, [routineId]),
            returnValue: _i3.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(
                this,
                Invocation.method(#getFullRoutine, [routineId]),
              ),
            ),
          )
          as _i3.Future<_i2.RoutineDto>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [ClientHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientHelper extends _i1.Mock implements _i8.ClientHelper {
  MockClientHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<T> getHandler<T>(
    String? api,
    String? urlPart,
    T Function(Map<String, dynamic>)? fromJson, {
    bool? needsHeader = true,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getHandler,
              [api, urlPart, fromJson],
              {#needsHeader: needsHeader, #queryParams: queryParams},
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getHandler,
                      [api, urlPart, fromJson],
                      {#needsHeader: needsHeader, #queryParams: queryParams},
                    ),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(
                    #getHandler,
                    [api, urlPart, fromJson],
                    {#needsHeader: needsHeader, #queryParams: queryParams},
                  ),
                ),
          )
          as _i3.Future<T>);

  @override
  _i3.Future<List<T>> getListHandler<T>(
    String? api,
    String? urlPart,
    T Function(Map<String, dynamic>)? fromJson, {
    bool? needsHeader = true,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getListHandler,
              [api, urlPart, fromJson],
              {#needsHeader: needsHeader, #queryParams: queryParams},
            ),
            returnValue: _i3.Future<List<T>>.value(<T>[]),
          )
          as _i3.Future<List<T>>);

  @override
  _i3.Future<T?> postHandler<T>(
    String? api,
    String? urlPart,
    Map<String, dynamic>? body, {
    T Function(Map<String, dynamic>)? fromJson,
    void Function(Map<String, dynamic>)? orElse,
    bool? needsHeader = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postHandler,
              [api, urlPart, body],
              {#fromJson: fromJson, #orElse: orElse, #needsHeader: needsHeader},
            ),
            returnValue: _i3.Future<T?>.value(),
          )
          as _i3.Future<T?>);

  @override
  _i3.Future<void> putHandler(
    String? api,
    String? urlPart,
    Map<String, dynamic>? body, {
    bool? needsHeader = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putHandler,
              [api, urlPart, body],
              {#needsHeader: needsHeader},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteHandler(
    String? api,
    String? urlPart,
    Map<String, dynamic>? body, {
    bool? needsHeader = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteHandler,
              [api, urlPart, body],
              {#needsHeader: needsHeader},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
