// Mocks generated by Mockito 5.4.6 from annotations
// in uniceps/test/app/data/stores/routine/routine_management_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:uniceps/app/data/models/routine_models/routine_dto.dart' as _i2;
import 'package:uniceps/app/data/models/routine_result.dart' as _i7;
import 'package:uniceps/app/data/sources/local/dal_routine/routine_management_local_source.dart'
    as _i5;
import 'package:uniceps/app/data/sources/services/internet_client/client_helper.dart'
    as _i8;
import 'package:uniceps/app/domain/classes/routine_classes/routine_heat.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRoutineDto_0 extends _i1.SmartFake implements _i2.RoutineDto {
  _FakeRoutineDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressCheckResult_2 extends _i1.SmartFake
    implements _i3.AddressCheckResult {
  _FakeAddressCheckResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_3<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IRoutineManagementLocalSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRoutineManagementLocalSourceContract extends _i1.Mock
    implements _i5.IRoutineManagementLocalSourceContract {
  MockIRoutineManagementLocalSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.RoutineDto>> getAllRoutines() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutines, []),
            returnValue: _i4.Future<List<_i2.RoutineDto>>.value(
              <_i2.RoutineDto>[],
            ),
          )
          as _i4.Future<List<_i2.RoutineDto>>);

  @override
  _i4.Future<List<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>>
  getAllRoutinesWithHeat() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutinesWithHeat, []),
            returnValue:
                _i4.Future<
                  List<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>
                >.value(<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>[]),
          )
          as _i4.Future<
            List<({_i6.RoutineHeat heat, _i2.RoutineDto routine})>
          >);

  @override
  _i4.Future<_i2.RoutineDto> createRoutine(String? routineName) =>
      (super.noSuchMethod(
            Invocation.method(#createRoutine, [routineName]),
            returnValue: _i4.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(
                this,
                Invocation.method(#createRoutine, [routineName]),
              ),
            ),
          )
          as _i4.Future<_i2.RoutineDto>);

  @override
  _i4.Future<_i2.RoutineDto> updateRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#updateRoutine, [dto]),
            returnValue: _i4.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(this, Invocation.method(#updateRoutine, [dto])),
            ),
          )
          as _i4.Future<_i2.RoutineDto>);

  @override
  _i4.Future<void> setCurrentRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentRoutine, [dto]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoutine, [dto]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i7.Stage> insertFullRoutine(_i2.RoutineDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#insertFullRoutine, [dto]),
            returnValue: _i4.Stream<_i7.Stage>.empty(),
          )
          as _i4.Stream<_i7.Stage>);

  @override
  _i4.Future<_i2.RoutineDto> getFullRoutine(int? routineId) =>
      (super.noSuchMethod(
            Invocation.method(#getFullRoutine, [routineId]),
            returnValue: _i4.Future<_i2.RoutineDto>.value(
              _FakeRoutineDto_0(
                this,
                Invocation.method(#getFullRoutine, [routineId]),
              ),
            ),
          )
          as _i4.Future<_i2.RoutineDto>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i3.InternetConnectionChecker {
  MockInternetConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get requireAllAddressesToRespond =>
      (super.noSuchMethod(
            Invocation.getter(#requireAllAddressesToRespond),
            returnValue: false,
          )
          as bool);

  @override
  bool get enableToCheckForSlowConnection =>
      (super.noSuchMethod(
            Invocation.getter(#enableToCheckForSlowConnection),
            returnValue: false,
          )
          as bool);

  @override
  Duration get slowConnectionThreshold =>
      (super.noSuchMethod(
            Invocation.getter(#slowConnectionThreshold),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#slowConnectionThreshold),
            ),
          )
          as Duration);

  @override
  Duration get checkTimeout =>
      (super.noSuchMethod(
            Invocation.getter(#checkTimeout),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#checkTimeout),
            ),
          )
          as Duration);

  @override
  Duration get checkInterval =>
      (super.noSuchMethod(
            Invocation.getter(#checkInterval),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#checkInterval),
            ),
          )
          as Duration);

  @override
  List<_i3.AddressCheckOption> get addresses =>
      (super.noSuchMethod(
            Invocation.getter(#addresses),
            returnValue: <_i3.AddressCheckOption>[],
          )
          as List<_i3.AddressCheckOption>);

  @override
  _i4.Stream<_i3.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
            Invocation.getter(#onStatusChange),
            returnValue: _i4.Stream<_i3.InternetConnectionStatus>.empty(),
          )
          as _i4.Stream<_i3.InternetConnectionStatus>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> get hasConnection =>
      (super.noSuchMethod(
            Invocation.getter(#hasConnection),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i3.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i4.Future<_i3.InternetConnectionStatus>.value(
              _i3.InternetConnectionStatus.connected,
            ),
          )
          as _i4.Future<_i3.InternetConnectionStatus>);

  @override
  set requireAllAddressesToRespond(bool? value) => super.noSuchMethod(
    Invocation.setter(#requireAllAddressesToRespond, value),
    returnValueForMissingStub: null,
  );

  @override
  set enableToCheckForSlowConnection(bool? value) => super.noSuchMethod(
    Invocation.setter(#enableToCheckForSlowConnection, value),
    returnValueForMissingStub: null,
  );

  @override
  set slowConnectionThreshold(Duration? value) => super.noSuchMethod(
    Invocation.setter(#slowConnectionThreshold, value),
    returnValueForMissingStub: null,
  );

  @override
  set checkTimeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#checkTimeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set checkInterval(Duration? value) => super.noSuchMethod(
    Invocation.setter(#checkInterval, value),
    returnValueForMissingStub: null,
  );

  @override
  set addresses(List<_i3.AddressCheckOption>? value) => super.noSuchMethod(
    Invocation.setter(#addresses, value),
    returnValueForMissingStub: null,
  );

  @override
  set setLastStatus(_i3.InternetConnectionStatus? status) => super.noSuchMethod(
    Invocation.setter(#setLastStatus, status),
    returnValueForMissingStub: null,
  );

  @override
  set setRequireAllAddressesToRespond(bool? value) => super.noSuchMethod(
    Invocation.setter(#setRequireAllAddressesToRespond, value),
    returnValueForMissingStub: null,
  );

  @override
  Iterable<_i4.Future<_i3.AddressCheckResult>> createAddressCheckFutures(
    List<_i3.AddressCheckOption>? addresses,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createAddressCheckFutures, [addresses]),
            returnValue: <_i4.Future<_i3.AddressCheckResult>>[],
          )
          as Iterable<_i4.Future<_i3.AddressCheckResult>>);

  @override
  _i4.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i3.AddressCheckResult> isHostReachable(
    _i3.AddressCheckOption? option,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isHostReachable, [option]),
            returnValue: _i4.Future<_i3.AddressCheckResult>.value(
              _FakeAddressCheckResult_2(
                this,
                Invocation.method(#isHostReachable, [option]),
              ),
            ),
          )
          as _i4.Future<_i3.AddressCheckResult>);

  @override
  _i4.Future<void> maybeEmitStatusUpdate({
    _i4.Timer? timer,
    Function? cancelCallback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#maybeEmitStatusUpdate, [], {
              #timer: timer,
              #cancelCallback: cancelCallback,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void emitStatus(_i3.InternetConnectionStatus? newStatus) =>
      super.noSuchMethod(
        Invocation.method(#emitStatus, [newStatus]),
        returnValueForMissingStub: null,
      );

  @override
  void startMonitoring() => super.noSuchMethod(
    Invocation.method(#startMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void cancelStatusUpdate() => super.noSuchMethod(
    Invocation.method(#cancelStatusUpdate, []),
    returnValueForMissingStub: null,
  );

  @override
  void configure({
    Duration? timeout,
    Duration? interval,
    List<_i3.AddressCheckOption>? addresses,
    _i3.SlowConnectionConfig? slowConnectionConfig,
  }) => super.noSuchMethod(
    Invocation.method(#configure, [], {
      #timeout: timeout,
      #interval: interval,
      #addresses: addresses,
      #slowConnectionConfig: slowConnectionConfig,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ClientHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientHelper extends _i1.Mock implements _i8.ClientHelper {
  MockClientHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<T> getHandler<T>(
    String? api,
    String? urlPart,
    T Function(Map<String, dynamic>)? fromJson, {
    bool? needsHeader = true,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getHandler,
              [api, urlPart, fromJson],
              {#needsHeader: needsHeader, #queryParams: queryParams},
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #getHandler,
                      [api, urlPart, fromJson],
                      {#needsHeader: needsHeader, #queryParams: queryParams},
                    ),
                  ),
                  (T v) => _i4.Future<T>.value(v),
                ) ??
                _FakeFuture_3<T>(
                  this,
                  Invocation.method(
                    #getHandler,
                    [api, urlPart, fromJson],
                    {#needsHeader: needsHeader, #queryParams: queryParams},
                  ),
                ),
          )
          as _i4.Future<T>);

  @override
  _i4.Future<List<T>> getListHandler<T>(
    String? api,
    String? urlPart,
    T Function(Map<String, dynamic>)? fromJson, {
    bool? needsHeader = true,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getListHandler,
              [api, urlPart, fromJson],
              {#needsHeader: needsHeader, #queryParams: queryParams},
            ),
            returnValue: _i4.Future<List<T>>.value(<T>[]),
          )
          as _i4.Future<List<T>>);

  @override
  _i4.Future<T?> postHandler<T>(
    String? api,
    String? urlPart,
    Map<String, dynamic>? body, {
    T Function(Map<String, dynamic>)? fromJson,
    void Function(Map<String, dynamic>)? orElse,
    bool? needsHeader = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postHandler,
              [api, urlPart, body],
              {#fromJson: fromJson, #orElse: orElse, #needsHeader: needsHeader},
            ),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<void> putHandler(
    String? api,
    String? urlPart,
    Map<String, dynamic>? body, {
    bool? needsHeader = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putHandler,
              [api, urlPart, body],
              {#needsHeader: needsHeader},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteHandler(
    String? api,
    String? urlPart,
    Map<String, dynamic>? body, {
    bool? needsHeader = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteHandler,
              [api, urlPart, body],
              {#needsHeader: needsHeader},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
